# SPDX-FileCopyrightText: 2024 Eric Dejouhanet <eric.dejouhanet@gmail.com>
# SPDX-License-Identifier: GPL-2.0-or-later

Dependencies:
- 'on': ['Linux/Qt5','Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kguidaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kinit': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kplotting': '@stable'

Options:
  in-source-build: False