# SPDX-FileCopyrightText: 2022 Nicolás Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kplotting': '@stable'
    'frameworks/knotifications': '@stable'

Options:
  run-cppcheck: False
