# SPDX-FileCopyrightText: 2024 Jasem Mutlaq <mutlaqja@ikarustech.com>
#                         2025-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kstars
version: 3.8.2
confinement: strict
base: core24
adopt-info: kstars

apps:
  kstars:
    extensions:
      - kde-neon-6
    common-id: org.kde.kstars.desktop
    desktop: usr/share/applications/org.kde.kstars.desktop
    command: usr/bin/kstars
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - unity7
      - joystick
      - pulseaudio
      - serial-port
      - camera
      - gpio
      - hardware-observe
      - hidraw
      - i2c
      - password-manager-service
      - location-control
      - location-observe
      - raw-usb
      - desktop
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kstars
    bus: session
parts:
  stellarsolver:
    source: https://github.com/rlancaste/stellarsolver.git
    plugin: cmake
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libcfitsio-dev
      - libgsl-dev
      - wcslib-dev
    stage-packages:
      - rsync
      - libpopt0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DUSE_QT5=OFF
    override-stage: |
        craftctl default
        rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
    prime:
      - -usr/bin/rsync

  kstars:
    after:
      - stellarsolver
    parse-info:
      - usr/share/metainfo/org.kde.kstars.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kde-qt6-core24-sdk/current\\;/snap/kf6-core24-sdk/current\\;/usr"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE\\;/snap/kde-qt6-core24-sdk/current\\;/snap/kf6-core24-sdk/current\\;/usr"
    build-packages:
      - libeigen3-dev
      - zlib1g-dev
      - libcfitsio-dev
      - libnova-dev
      - libgsl-dev
      - libindi-dev
      - wcslib-dev
      - libraw-dev
      - libxkbcommon-dev
      - libcurl4-gnutls-dev
    stage-packages:
      - astrometry.net
      - indi-bin
      - xplanet
      - libcfitsio10t64
      - libnova-0.16-0
      - libgsl27
      - libpgsbox8
      - libwcs8
      - libraw23t64
      - libxkbcommon0
      - libcurl3t64-gnutls
    override-pull: |
      craftctl default
      while read -r PATCHFILE ; do
        patch -p1 < "$CRAFT_PROJECT_DIR/snap/local/patches/$PATCHFILE"
      done < $CRAFT_PROJECT_DIR/snap/local/patches/series
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [kstars]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kstars
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
