#ifndef FITSCOMMON_H
#define FITSCOMMON_H

enum FITSMode { FITS_NORMAL, FITS_FOCUS };
enum FITSBar  { FITS_POSITION, FITS_VALUE, FITS_RESOLUTION, FITS_ZOOM, FITS_MESSAGE };
enum FITSScale { FITSAuto = 0 , FITSLinear, FITSLog, FITSSqrt, FITSCustom };
enum FITSZoom { ZOOM_FIT_WINDOW, ZOOM_KEEP_LEVEL, ZOOM_FULL };

#endif // FITSCOMMON_H
