# Common rules

.optional-on-forked-repository:
  rules:
    - if: $CI_PROJECT_NAMESPACE !~ "education"
      when: manual
      allow_failure: true

.optional-on-draft-merge-requests:
  rules:
    - if: $CI_MERGE_REQUEST_DRAFT == "true" || $CI_MERGE_REQUEST_TITLE =~ "Draft"
      when: manual
      allow_failure: true

.always-on-scheduled-pipeline:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always

.always-on-merge-requests:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

.never-on-merge-requests:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never

.always-on-master-branch:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

.always-on-stable-release:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^stable-.*/
      when: always

.manual-skipped-recipe:
  rules:
    - when: manual
      allow_failure: true

.manual-required-recipe:
  rules:
    - when: manual
      allow_failure: false

.standard-build-recipes:
  rules:
    - !reference [.optional-on-forked-repository, rules]
    - !reference [.optional-on-draft-merge-requests, rules]
    - !reference [.always-on-scheduled-pipeline, rules]
    - !reference [.always-on-master-branch, rules]
    - !reference [.always-on-merge-requests, rules]
    - !reference [.manual-skipped-recipe, rules]

.craft-recipes:
  rules:
    - !reference [.optional-on-forked-repository, rules]
    - !reference [.optional-on-draft-merge-requests, rules]
    - !reference [.always-on-scheduled-pipeline, rules]
    - !reference [.always-on-master-branch, rules]
    - !reference [.always-on-stable-release, rules]
    - !reference [.manual-skipped-recipe, rules]

.publishing-recipes:
  rules:
    - !reference [.always-on-stable-release, rules]
    - when: never

.custom-build-recipes:
  rules:
    - !reference [.optional-on-forked-repository, rules]
    - !reference [.optional-on-draft-merge-requests, rules]
    - !reference [.always-on-merge-requests, rules]
    - !reference [.manual-skipped-recipe, rules]