i18nc("string from libindi, used in the config dialog", "100x");
i18nc("string from libindi, used in the config dialog", "10x");
i18nc("string from libindi, used in the config dialog", "1200x");
i18nc("string from libindi, used in the config dialog", "12x");
i18nc("string from libindi, used in the config dialog", "600x");
i18nc("string from libindi, used in the config dialog", "64x");
i18nc("string from libindi, used in the config dialog", "900x");
i18nc("string from libindi, used in the config dialog", ":CM#");
i18nc("string from libindi, used in the config dialog", ":CMR#");
i18nc("string from libindi, used in the config dialog", "AP UTC Offset");
i18nc("string from libindi, used in the config dialog", "AP local time");
i18nc("string from libindi, used in the config dialog", "AP sidereal time");
i18nc("string from libindi, used in the config dialog", "Abell");
i18nc("string from libindi, used in the config dialog", "Abort Motion");
i18nc("string from libindi, used in the config dialog", "Abort Slew");
i18nc("string from libindi, used in the config dialog", "Abort Slew/Track");
i18nc("string from libindi, used in the config dialog", "Abort");
i18nc("string from libindi, used in the config dialog", "Absolute Position");
i18nc("string from libindi, used in the config dialog", "Activate");
i18nc("string from libindi, used in the config dialog", "Active Filter");
i18nc("string from libindi, used in the config dialog", "Actual Time");
i18nc("string from libindi, used in the config dialog", "Alignment");
i18nc("string from libindi, used in the config dialog", "Alt  D:M:S");
i18nc("string from libindi, used in the config dialog", "Alt/Dec Anti-backlash");
i18nc("string from libindi, used in the config dialog", "Alt/Dec PEC");
i18nc("string from libindi, used in the config dialog", "AltAz");
i18nc("string from libindi, used in the config dialog", "Anti Flicker");
i18nc("string from libindi, used in the config dialog", "Aperture (mm)");
i18nc("string from libindi, used in the config dialog", "Arp");
i18nc("string from libindi, used in the config dialog", "Atmosphere");
i18nc("string from libindi, used in the config dialog", "Auto");
i18nc("string from libindi, used in the config dialog", "Auxiliary");
i18nc("string from libindi, used in the config dialog", "Az D:M:S");
i18nc("string from libindi, used in the config dialog", "Az/Ra Anti-backlash");
i18nc("string from libindi, used in the config dialog", "Az/Ra PEC");
i18nc("string from libindi, used in the config dialog", "Back Light");
i18nc("string from libindi, used in the config dialog", "Backlash");
i18nc("string from libindi, used in the config dialog", "Bias");
i18nc("string from libindi, used in the config dialog", "Binning");
i18nc("string from libindi, used in the config dialog", "Bits per pixel");
i18nc("string from libindi, used in the config dialog", "Blue");
i18nc("string from libindi, used in the config dialog", "Brightness");
i18nc("string from libindi, used in the config dialog", "CCD Bias");
i18nc("string from libindi, used in the config dialog", "CCD Information");
i18nc("string from libindi, used in the config dialog", "CCD Maximum ADU");
i18nc("string from libindi, used in the config dialog", "CCD Noise");
i18nc("string from libindi, used in the config dialog", "CCD Simulator");
i18nc("string from libindi, used in the config dialog", "CCD X Pixel Size");
i18nc("string from libindi, used in the config dialog", "CCD X resolution");
i18nc("string from libindi, used in the config dialog", "CCD Y Pixel Size");
i18nc("string from libindi, used in the config dialog", "CCD Y resolution");
i18nc("string from libindi, used in the config dialog", "CCD1");
i18nc("string from libindi, used in the config dialog", "CCDs");
i18nc("string from libindi, used in the config dialog", "Caldwell");
i18nc("string from libindi, used in the config dialog", "Camera Model");
i18nc("string from libindi, used in the config dialog", "Celsius");
i18nc("string from libindi, used in the config dialog", "Centering");
i18nc("string from libindi, used in the config dialog", "Color");
i18nc("string from libindi, used in the config dialog", "Comet DEC motion arcmin/day");
i18nc("string from libindi, used in the config dialog", "Comet RA motion arcmin/day");
i18nc("string from libindi, used in the config dialog", "Comet tracking parameters");
i18nc("string from libindi, used in the config dialog", "Comet");
i18nc("string from libindi, used in the config dialog", "Communication");
i18nc("string from libindi, used in the config dialog", "Compress");
i18nc("string from libindi, used in the config dialog", "Compression");
i18nc("string from libindi, used in the config dialog", "Configuration");
i18nc("string from libindi, used in the config dialog", "Connect");
i18nc("string from libindi, used in the config dialog", "Connection");
i18nc("string from libindi, used in the config dialog", "Contrast");
i18nc("string from libindi, used in the config dialog", "Control");
i18nc("string from libindi, used in the config dialog", "Count");
i18nc("string from libindi, used in the config dialog", "DEC (dd:mm:ss)");
i18nc("string from libindi, used in the config dialog", "Dark");
i18nc("string from libindi, used in the config dialog", "Date");
i18nc("string from libindi, used in the config dialog", "Date/Time");
i18nc("string from libindi, used in the config dialog", "Date/Time/Location");
i18nc("string from libindi, used in the config dialog", "Debug");
i18nc("string from libindi, used in the config dialog", "Dec (arcmin)");
i18nc("string from libindi, used in the config dialog", "Dec (dd:mm:ss)");
i18nc("string from libindi, used in the config dialog", "Dec D:M:S");
i18nc("string from libindi, used in the config dialog", "Declination axis");
i18nc("string from libindi, used in the config dialog", "Deep Sky Catalogs");
i18nc("string from libindi, used in the config dialog", "Default");
i18nc("string from libindi, used in the config dialog", "Device");
i18nc("string from libindi, used in the config dialog", "Diff. Eq.");
i18nc("string from libindi, used in the config dialog", "Direction");
i18nc("string from libindi, used in the config dialog", "Disable");
i18nc("string from libindi, used in the config dialog", "Disconnect");
i18nc("string from libindi, used in the config dialog", "Dome control");
i18nc("string from libindi, used in the config dialog", "Duration (s)");
i18nc("string from libindi, used in the config dialog", "Duty cycle");
i18nc("string from libindi, used in the config dialog", "EQ Coord");
i18nc("string from libindi, used in the config dialog", "EQ PEC");
i18nc("string from libindi, used in the config dialog", "East (msec)");
i18nc("string from libindi, used in the config dialog", "East (sec)");
i18nc("string from libindi, used in the config dialog", "East");
i18nc("string from libindi, used in the config dialog", "East/West");
i18nc("string from libindi, used in the config dialog", "Enable");
i18nc("string from libindi, used in the config dialog", "Eq. Coordinates");
i18nc("string from libindi, used in the config dialog", "Equatorial JNow");
i18nc("string from libindi, used in the config dialog", "Expose");
i18nc("string from libindi, used in the config dialog", "Expose Abort");
i18nc("string from libindi, used in the config dialog", "Exposure");
i18nc("string from libindi, used in the config dialog", "Extended GPS Features");
i18nc("string from libindi, used in the config dialog", "Extrema");
i18nc("string from libindi, used in the config dialog", "FWHM (arcseconds)");
i18nc("string from libindi, used in the config dialog", "FWHM");
i18nc("string from libindi, used in the config dialog", "Factory");
i18nc("string from libindi, used in the config dialog", "Fan");
i18nc("string from libindi, used in the config dialog", "Fast");
i18nc("string from libindi, used in the config dialog", "Feed");
i18nc("string from libindi, used in the config dialog", "Feedback");
i18nc("string from libindi, used in the config dialog", "Field De-rotator");
i18nc("string from libindi, used in the config dialog", "Filter #1");
i18nc("string from libindi, used in the config dialog", "Filter #2");
i18nc("string from libindi, used in the config dialog", "Filter #3");
i18nc("string from libindi, used in the config dialog", "Filter #4");
i18nc("string from libindi, used in the config dialog", "Filter #5");
i18nc("string from libindi, used in the config dialog", "Filter Count");
i18nc("string from libindi, used in the config dialog", "Filter Simulator");
i18nc("string from libindi, used in the config dialog", "Filter Wheel");
i18nc("string from libindi, used in the config dialog", "Filter");
i18nc("string from libindi, used in the config dialog", "Find");
i18nc("string from libindi, used in the config dialog", "Firmware Info");
i18nc("string from libindi, used in the config dialog", "Firmware data");
i18nc("string from libindi, used in the config dialog", "Firmware version");
i18nc("string from libindi, used in the config dialog", "Firmware");
i18nc("string from libindi, used in the config dialog", "Flat");
i18nc("string from libindi, used in the config dialog", "Fluorescent");
i18nc("string from libindi, used in the config dialog", "Focal Length (mm)");
i18nc("string from libindi, used in the config dialog", "Focal Length (mm)");
i18nc("string from libindi, used in the config dialog", "Focus Control");
i18nc("string from libindi, used in the config dialog", "Focus In");
i18nc("string from libindi, used in the config dialog", "Focus Out");
i18nc("string from libindi, used in the config dialog", "Focus Speed");
i18nc("string from libindi, used in the config dialog", "Focus Timer");
i18nc("string from libindi, used in the config dialog", "Focus in");
i18nc("string from libindi, used in the config dialog", "Focus out");
i18nc("string from libindi, used in the config dialog", "Focuser Simulator");
i18nc("string from libindi, used in the config dialog", "Focuser");
i18nc("string from libindi, used in the config dialog", "Focusers");
i18nc("string from libindi, used in the config dialog", "Frame Rate");
i18nc("string from libindi, used in the config dialog", "Frame");
i18nc("string from libindi, used in the config dialog", "FrameType");
i18nc("string from libindi, used in the config dialog", "Freq");
i18nc("string from libindi, used in the config dialog", "Full");
i18nc("string from libindi, used in the config dialog", "GCVS");
i18nc("string from libindi, used in the config dialog", "GOTO");
i18nc("string from libindi, used in the config dialog", "GPS Power");
i18nc("string from libindi, used in the config dialog", "GPS Status");
i18nc("string from libindi, used in the config dialog", "GPS System");
i18nc("string from libindi, used in the config dialog", "GPS/16 inch Features");
i18nc("string from libindi, used in the config dialog", "Gamma");
i18nc("string from libindi, used in the config dialog", "Generic Video4Linux");
i18nc("string from libindi, used in the config dialog", "Geographic Location");
i18nc("string from libindi, used in the config dialog", "Geographic Location");
i18nc("string from libindi, used in the config dialog", "Goto");
i18nc("string from libindi, used in the config dialog", "Green");
i18nc("string from libindi, used in the config dialog", "Grey");
i18nc("string from libindi, used in the config dialog", "Guide Abort");
i18nc("string from libindi, used in the config dialog", "Guide East/West");
i18nc("string from libindi, used in the config dialog", "Guide Head");
i18nc("string from libindi, used in the config dialog", "Guide North/South");
i18nc("string from libindi, used in the config dialog", "Guide West/East");
i18nc("string from libindi, used in the config dialog", "Guide Wheel");
i18nc("string from libindi, used in the config dialog", "Guide");
i18nc("string from libindi, used in the config dialog", "Guider Aperture (mm)");
i18nc("string from libindi, used in the config dialog", "Guider Control");
i18nc("string from libindi, used in the config dialog", "Guider Focal Length (mm)");
i18nc("string from libindi, used in the config dialog", "Guider Image");
i18nc("string from libindi, used in the config dialog", "H Alpha");
i18nc("string from libindi, used in the config dialog", "H:M:S");
i18nc("string from libindi, used in the config dialog", "HA H:M:S");
i18nc("string from libindi, used in the config dialog", "Halt");
i18nc("string from libindi, used in the config dialog", "Height m");
i18nc("string from libindi, used in the config dialog", "Height");
i18nc("string from libindi, used in the config dialog", "High");
i18nc("string from libindi, used in the config dialog", "Horizontal Coords");
i18nc("string from libindi, used in the config dialog", "Hour axis");
i18nc("string from libindi, used in the config dialog", "Hourangle Coords");
i18nc("string from libindi, used in the config dialog", "Hue");
i18nc("string from libindi, used in the config dialog", "Humidity Perc.");
i18nc("string from libindi, used in the config dialog", "IC");
i18nc("string from libindi, used in the config dialog", "Image Adjustments");
i18nc("string from libindi, used in the config dialog", "Image Control");
i18nc("string from libindi, used in the config dialog", "Image Data");
i18nc("string from libindi, used in the config dialog", "Image Info");
i18nc("string from libindi, used in the config dialog", "Image Settings");
i18nc("string from libindi, used in the config dialog", "Image Type");
i18nc("string from libindi, used in the config dialog", "Image");
i18nc("string from libindi, used in the config dialog", "Indoor");
i18nc("string from libindi, used in the config dialog", "Info");
i18nc("string from libindi, used in the config dialog", "Jupiter");
i18nc("string from libindi, used in the config dialog", "LX200 Basic");
i18nc("string from libindi, used in the config dialog", "Lat (dd:mm:ss)");
i18nc("string from libindi, used in the config dialog", "Lat.  D:M:S +N");
i18nc("string from libindi, used in the config dialog", "Lat. D:M:S +N");
i18nc("string from libindi, used in the config dialog", "Left ");
i18nc("string from libindi, used in the config dialog", "Library");
i18nc("string from libindi, used in the config dialog", "Light");
i18nc("string from libindi, used in the config dialog", "Limiting Mag");
i18nc("string from libindi, used in the config dialog", "Load");
i18nc("string from libindi, used in the config dialog", "Lon (dd:mm:ss)");
i18nc("string from libindi, used in the config dialog", "Long. D:M:S +E");
i18nc("string from libindi, used in the config dialog", "Low");
i18nc("string from libindi, used in the config dialog", "Luminosity");
i18nc("string from libindi, used in the config dialog", "Lunar");
i18nc("string from libindi, used in the config dialog", "Main Control");
i18nc("string from libindi, used in the config dialog", "Manual Blue");
i18nc("string from libindi, used in the config dialog", "Manual Red");
i18nc("string from libindi, used in the config dialog", "Manual");
i18nc("string from libindi, used in the config dialog", "Mars");
i18nc("string from libindi, used in the config dialog", "Master alarm");
i18nc("string from libindi, used in the config dialog", "Max slew Rate");
i18nc("string from libindi, used in the config dialog", "Max");
i18nc("string from libindi, used in the config dialog", "Max. travel");
i18nc("string from libindi, used in the config dialog", "Maximum Tick");
i18nc("string from libindi, used in the config dialog", "Maximum travel");
i18nc("string from libindi, used in the config dialog", "Medium");
i18nc("string from libindi, used in the config dialog", "Mercury");
i18nc("string from libindi, used in the config dialog", "Messier");
i18nc("string from libindi, used in the config dialog", "Minimum Tick");
i18nc("string from libindi, used in the config dialog", "Mode");
i18nc("string from libindi, used in the config dialog", "Model");
i18nc("string from libindi, used in the config dialog", "Moon");
i18nc("string from libindi, used in the config dialog", "Motion Control");
i18nc("string from libindi, used in the config dialog", "Motion");
i18nc("string from libindi, used in the config dialog", "Motor Steps");
i18nc("string from libindi, used in the config dialog", "Motor steps per tick");
i18nc("string from libindi, used in the config dialog", "Mount coordinates");
i18nc("string from libindi, used in the config dialog", "Mount init.");
i18nc("string from libindi, used in the config dialog", "Mounting");
i18nc("string from libindi, used in the config dialog", "Move to rate");
i18nc("string from libindi, used in the config dialog", "Movement Control");
i18nc("string from libindi, used in the config dialog", "NGC");
i18nc("string from libindi, used in the config dialog", "Name");
i18nc("string from libindi, used in the config dialog", "Neptune");
i18nc("string from libindi, used in the config dialog", "Noise Reduction");
i18nc("string from libindi, used in the config dialog", "None");
i18nc("string from libindi, used in the config dialog", "North (msec)");
i18nc("string from libindi, used in the config dialog", "North (sec)");
i18nc("string from libindi, used in the config dialog", "North");
i18nc("string from libindi, used in the config dialog", "North/South");
i18nc("string from libindi, used in the config dialog", "Note");
i18nc("string from libindi, used in the config dialog", "Number");
i18nc("string from libindi, used in the config dialog", "OFF");
i18nc("string from libindi, used in the config dialog", "ON");
i18nc("string from libindi, used in the config dialog", "OTA Temperature (C)");
i18nc("string from libindi, used in the config dialog", "OTA Update");
i18nc("string from libindi, used in the config dialog", "Oag Offset (arcminutes)");
i18nc("string from libindi, used in the config dialog", "Oag Offset (arminutes)");
i18nc("string from libindi, used in the config dialog", "Object Info");
i18nc("string from libindi, used in the config dialog", "Object Number");
i18nc("string from libindi, used in the config dialog", "Object");
i18nc("string from libindi, used in the config dialog", "Off");
i18nc("string from libindi, used in the config dialog", "Offset");
i18nc("string from libindi, used in the config dialog", "On Set");
i18nc("string from libindi, used in the config dialog", "On");
i18nc("string from libindi, used in the config dialog", "Options");
i18nc("string from libindi, used in the config dialog", "Outdoor");
i18nc("string from libindi, used in the config dialog", "PE N/S");
i18nc("string from libindi, used in the config dialog", "PE W/E");
i18nc("string from libindi, used in the config dialog", "Park Scope");
i18nc("string from libindi, used in the config dialog", "Park");
i18nc("string from libindi, used in the config dialog", "Periodic Error");
i18nc("string from libindi, used in the config dialog", "Philips Webcam");
i18nc("string from libindi, used in the config dialog", "Pixel size (um)");
i18nc("string from libindi, used in the config dialog", "Pixel size X");
i18nc("string from libindi, used in the config dialog", "Pixel size Y");
i18nc("string from libindi, used in the config dialog", "Pluto");
i18nc("string from libindi, used in the config dialog", "Polar");
i18nc("string from libindi, used in the config dialog", "Port");
i18nc("string from libindi, used in the config dialog", "Ports");
i18nc("string from libindi, used in the config dialog", "Position");
i18nc("string from libindi, used in the config dialog", "Power");
i18nc("string from libindi, used in the config dialog", "Pressure hPa");
i18nc("string from libindi, used in the config dialog", "Property");
i18nc("string from libindi, used in the config dialog", "RA  H:M:S");
i18nc("string from libindi, used in the config dialog", "RA (arcmin)");
i18nc("string from libindi, used in the config dialog", "RA (hh:mm:ss)");
i18nc("string from libindi, used in the config dialog", "RA H:M:S");
i18nc("string from libindi, used in the config dialog", "RA motor");
i18nc("string from libindi, used in the config dialog", "Ra (hh:mm:ss)");
i18nc("string from libindi, used in the config dialog", "Rate");
i18nc("string from libindi, used in the config dialog", "Raw");
i18nc("string from libindi, used in the config dialog", "Red");
i18nc("string from libindi, used in the config dialog", "Relative Position");
i18nc("string from libindi, used in the config dialog", "Resolution x");
i18nc("string from libindi, used in the config dialog", "Resolution y");
i18nc("string from libindi, used in the config dialog", "Restart");
i18nc("string from libindi, used in the config dialog", "Restore");
i18nc("string from libindi, used in the config dialog", "SAO");
i18nc("string from libindi, used in the config dialog", "STAR");
i18nc("string from libindi, used in the config dialog", "Saturation Mag");
i18nc("string from libindi, used in the config dialog", "Saturn");
i18nc("string from libindi, used in the config dialog", "Save home");
i18nc("string from libindi, used in the config dialog", "Save");
i18nc("string from libindi, used in the config dialog", "Scope Location");
i18nc("string from libindi, used in the config dialog", "Scope Properties");
i18nc("string from libindi, used in the config dialog", "Seeing");
i18nc("string from libindi, used in the config dialog", "Select item...");
i18nc("string from libindi, used in the config dialog", "Select");
i18nc("string from libindi, used in the config dialog", "Selenographic Sync");
i18nc("string from libindi, used in the config dialog", "Set Register");
i18nc("string from libindi, used in the config dialog", "Set home");
i18nc("string from libindi, used in the config dialog", "Set register");
i18nc("string from libindi, used in the config dialog", "Set");
i18nc("string from libindi, used in the config dialog", "Settings");
i18nc("string from libindi, used in the config dialog", "Shutter Speed");
i18nc("string from libindi, used in the config dialog", "Sidereal");
i18nc("string from libindi, used in the config dialog", "Sidereal Time");
i18nc("string from libindi, used in the config dialog", "Sidereal time");
i18nc("string from libindi, used in the config dialog", "Simulation");
i18nc("string from libindi, used in the config dialog", "Simulator Config");
i18nc("string from libindi, used in the config dialog", "Simulator Settings");
i18nc("string from libindi, used in the config dialog", "Site 1");
i18nc("string from libindi, used in the config dialog", "Site 2");
i18nc("string from libindi, used in the config dialog", "Site 3");
i18nc("string from libindi, used in the config dialog", "Site 4");
i18nc("string from libindi, used in the config dialog", "Site Management");
i18nc("string from libindi, used in the config dialog", "Site Name");
i18nc("string from libindi, used in the config dialog", "Sites");
i18nc("string from libindi, used in the config dialog", "Sky Glow (magnitudes)");
i18nc("string from libindi, used in the config dialog", "Sleep");
i18nc("string from libindi, used in the config dialog", "Slew Accuracy");
i18nc("string from libindi, used in the config dialog", "Slew rate");
i18nc("string from libindi, used in the config dialog", "Slew");
i18nc("string from libindi, used in the config dialog", "Slow");
i18nc("string from libindi, used in the config dialog", "Snoop dc connection");
i18nc("string from libindi, used in the config dialog", "Snoop dc master alarm");
i18nc("string from libindi, used in the config dialog", "Snoop dc mode");
i18nc("string from libindi, used in the config dialog", "Snoop devices");
i18nc("string from libindi, used in the config dialog", "Solar System");
i18nc("string from libindi, used in the config dialog", "Solar");
i18nc("string from libindi, used in the config dialog", "South (msec)");
i18nc("string from libindi, used in the config dialog", "South (sec)");
i18nc("string from libindi, used in the config dialog", "South");
i18nc("string from libindi, used in the config dialog", "Speed");
i18nc("string from libindi, used in the config dialog", "Star Catalogs");
i18nc("string from libindi, used in the config dialog", "Step delay");
i18nc("string from libindi, used in the config dialog", "Stop");
i18nc("string from libindi, used in the config dialog", "Stream Off");
i18nc("string from libindi, used in the config dialog", "Stream On");
i18nc("string from libindi, used in the config dialog", "Swap buttons");
i18nc("string from libindi, used in the config dialog", "Switch 1");
i18nc("string from libindi, used in the config dialog", "Switch 2");
i18nc("string from libindi, used in the config dialog", "Switch 3");
i18nc("string from libindi, used in the config dialog", "Switch 4");
i18nc("string from libindi, used in the config dialog", "Sync");
i18nc("string from libindi, used in the config dialog", "Telescope Simulator");
i18nc("string from libindi, used in the config dialog", "Telescope");
i18nc("string from libindi, used in the config dialog", "Telescopes");
i18nc("string from libindi, used in the config dialog", "Temma Driver");
i18nc("string from libindi, used in the config dialog", "Temma version");
i18nc("string from libindi, used in the config dialog", "Temma");
i18nc("string from libindi, used in the config dialog", "Temp.");
i18nc("string from libindi, used in the config dialog", "Temperature K");
i18nc("string from libindi, used in the config dialog", "Theta D:M:S");
i18nc("string from libindi, used in the config dialog", "Ticks");
i18nc("string from libindi, used in the config dialog", "Time Factor");
i18nc("string from libindi, used in the config dialog", "Time");
i18nc("string from libindi, used in the config dialog", "Timer (ms)");
i18nc("string from libindi, used in the config dialog", "Timer");
i18nc("string from libindi, used in the config dialog", "Top");
i18nc("string from libindi, used in the config dialog", "Total Exposure Time (ms)");
i18nc("string from libindi, used in the config dialog", "Track Mode");
i18nc("string from libindi, used in the config dialog", "Track");
i18nc("string from libindi, used in the config dialog", "Tracking Accuracy");
i18nc("string from libindi, used in the config dialog", "Tracking Frequency");
i18nc("string from libindi, used in the config dialog", "Tracking Mode");
i18nc("string from libindi, used in the config dialog", "Tracking mode");
i18nc("string from libindi, used in the config dialog", "Transformation");
i18nc("string from libindi, used in the config dialog", "UGC");
i18nc("string from libindi, used in the config dialog", "UTC Offset");
i18nc("string from libindi, used in the config dialog", "UTC Time");
i18nc("string from libindi, used in the config dialog", "UTC");
i18nc("string from libindi, used in the config dialog", "Update Client");
i18nc("string from libindi, used in the config dialog", "Update GPS");
i18nc("string from libindi, used in the config dialog", "Update");
i18nc("string from libindi, used in the config dialog", "Uranus");
i18nc("string from libindi, used in the config dialog", "Use Pulse Cmd");
i18nc("string from libindi, used in the config dialog", "Venus");
i18nc("string from libindi, used in the config dialog", "Video Stream");
i18nc("string from libindi, used in the config dialog", "Video");
i18nc("string from libindi, used in the config dialog", "Wake up");
i18nc("string from libindi, used in the config dialog", "Webcam Name");
i18nc("string from libindi, used in the config dialog", "West (msec)");
i18nc("string from libindi, used in the config dialog", "West (sec)");
i18nc("string from libindi, used in the config dialog", "West");
i18nc("string from libindi, used in the config dialog", "West/East");
i18nc("string from libindi, used in the config dialog", "W/E Rate");
i18nc("string from libindi, used in the config dialog", "N/S Rate");
i18nc("string from libindi, used in the config dialog", "White Balance Mode");
i18nc("string from libindi, used in the config dialog", "White Balance");
i18nc("string from libindi, used in the config dialog", "Whiteness");
i18nc("string from libindi, used in the config dialog", "Width");
i18nc("string from libindi, used in the config dialog", "X");
i18nc("string from libindi, used in the config dialog", "Y");
i18nc("string from libindi, used in the config dialog", "app. to refracted");
i18nc("string from libindi, used in the config dialog", "app., refr., tel., observed");
i18nc("string from libindi, used in the config dialog", "app., refr., telescope");
i18nc("string from libindi, used in the config dialog", "arcseconds");
i18nc("string from libindi, used in the config dialog", "cold");
i18nc("string from libindi, used in the config dialog", "danger");
i18nc("string from libindi, used in the config dialog", "decPEC (dd:mm:ss)");
i18nc("string from libindi, used in the config dialog", "dome control");
i18nc("string from libindi, used in the config dialog", "identity");
i18nc("string from libindi, used in the config dialog", "lunar");
i18nc("string from libindi, used in the config dialog", "manual");
i18nc("string from libindi, used in the config dialog", "max Alt");
i18nc("string from libindi, used in the config dialog", "min Alt");
i18nc("string from libindi, used in the config dialog", "off");
i18nc("string from libindi, used in the config dialog", "on");
i18nc("string from libindi, used in the config dialog", "rel. to HA");
i18nc("string from libindi, used in the config dialog", "reset");
i18nc("string from libindi, used in the config dialog", "sidereal");
i18nc("string from libindi, used in the config dialog", "solar");
i18nc("string from libindi, used in the config dialog", "undefined");
i18nc("string from libindi, used in the config dialog", "warm");
