#!/bin/bash
# Building options. Set libraries that has to be downloaded and/or built
download_kf5=""
build_kf5=""
build_cfitsio=""
build_nova=""
download_indi=""
build_indi=""
build_libraw=""

kf5_android_path="/home/polaris/dev/KDE/test_kstarslite_building_script/KF5_Android/"

qt_android_libs="/home/polaris/dev/Qt5.7.0/5.7/android_armv7/"

android_architecture="arm" # arm/arm64 or x86/x86_64 or mips/mips64

android_ndk="/home/polaris/dev/Android/android-ndk-r11c/" #"Your path to Android NDK folder"

android_sdk_root="/home/polaris/dev/Android/android-sdk-linux/" #"Your path to Android SDK folder"

android_api_level="15"
 
ant= "usr/bin/ant" #"path to your ant installation (/usr/bin/ant on Ubuntu)"

java_home="/usr/lib/jvm/java-8-openjdk-amd64/" #"path to your JDK (choose from the folders at /usr/lib/jvm/ on Ubuntu)"

kstars_DIR="/home/polaris/dev/KDE/kstars/" #"KStars source directory"

build_dir="/home/polaris/dev/KDE/kstars-build/Android/Release/${android_architecture}" #"Your building directory (build and export directories will be created there)"

kf5_host_tooling="/usr/lib/x86_64-linux-gnu/cmake/" #"Path to KF5Config cmake files e.g. /usr/lib/x86_64-linux-gnu/cmake/"

indi_location="/home/polaris/dev/KDE/test_kstarslite_building_script/indi_test" # Set INDI source location (location of libindi with CMakeLists.txt in it)