---
name: kstars
version: 3.3.7
confinement: strict
grade: devel
base: core18
adopt-info: kstars
apps:
    kstars:
        command: kf5-launch kstars
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - serial-port
        - camera
        - gpio
        - hardware-observe
        - hidraw
        - i2c
        - location-control
        - location-observe
        - raw-usb
        - desktop
        - desktop-legacy
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kstars
        bus: session
plugs:
    kde-frameworks-5-plug:
        interface: content
        content: kde-frameworks-5-core18-all
        default-provider: kde-frameworks-5-core18
        target: kf5
parts:
    kstars:
        parse-info:
        - usr/share/metainfo/org.kde.kstars.appdata.xml
        build-snaps:
        - kde-frameworks-5-core18-sdk
        after:
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - qt5-default
        - libeigen3-dev
        - zlib1g-dev
        - libcfitsio-dev
        - libnova-dev
        - libgsl-dev
        - libindi-dev
        - qt5keychain-dev
        - wcslib-dev
        stage-packages:
        - astrometry.net
        - indi-bin
        - indi-full
        - xplanet
        - libcfitsio5
        - libnova-0.16-0
        - libgsl23
        - libindialignmentdriver1
        - libindidriver1
        - libpgsbox5
        - libwcs5
        - libqt5keychain1
        source: https://anongit.kde.org/kstars.git
        configflags:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DBUILD_DOC=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    kde-frameworks-5-env:
        plugin: dump
        source: https://anongit.kde.org/snap-kf5-launcher.git
